---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by leu.
--- DateTime: 04/04/18 18:42
---

--[[ Clean Database by Cjaker | Refactor and SQL Optimizations by Leu ]]--

local inactiveMonths = 1 --> Quantos meses o player ficou inativo
local createdMonths = 1 --> Quantos meses a conta foi criada e não possui character criado.
local protectedAccIdEnd = 1 --ignorar accounts com id <= 20
local function clearInactivePlayers()
    local inactiveTimestamp = os.time() - (86400 * (inactiveMonths*30))
    local totalClear=0

    local fromClause = "`players` WHERE `account_id` > ".. protectedAccIdEnd .." AND lastlogin <= "..inactiveTimestamp

    local resultId = db.storeQuery("SELECT COUNT(*) as num_inativos FROM "..fromClause)
    if resultId ~= false then
        totalClear = result.getDataInt(resultId, 'num_inativos')
        result.free(resultId)
        if totalClear > 0 then
            db.query("DELETE FROM "..fromClause)
        end
    end

    return totalClear
end

local function clearEmptyAccounts()
    local totalClear = 0
    local createdTimestamp = os.time() - (86400 * (createdMonths*30))

    local fromClause = "`accounts` ACCS WHERE `id` > ".. protectedAccIdEnd .." AND `creation` <= "..createdTimestamp.." AND (SELECT COUNT(*) from `players` WHERE `account_id` = ACCS.`id`) > 0"

    local resultId = db.storeQuery("SELECT COUNT(*) as num_inativas FROM "..fromClause)
    if resultId~= false then
        totalClear = result.getDataInt(resultId,'num_inativas')
        result.free(resultId)
        if totalClear > 0 then
            db.query("DELETE ACCS FROM "..fromClause)
        end
    end


    return totalClear
end

function onStartup()
    print('>> ' ..clearInactivePlayers().. " players inativos deletados.")
    print('>> ' ..clearEmptyAccounts().. " contas vazias deletadas.")
end